---
name: Dependency Review

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

permissions: {}

jobs:
  dependency-review:
    if: github.event.repository.private == false
    permissions:
      contents: read
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-dependency-review.yml@ee7af2fc5379dc235ced9f93378cbca973d9e5ad # v6.0.0
